CREATE TABLE CONFERENCES_SESSIONS (
		CONFERENCE_ID DECIMAL(19 , 2) NOT NULL,
		SESSION_ID DECIMAL(19 , 2) NOT NULL
	);

CREATE TABLE SPEAKERS (
		ID DECIMAL(19 , 2) NOT NULL,
		ABOUT VARCHAR(4096),
		FIRSTNAME VARCHAR(255),
		LASTNAME VARCHAR(255),
		PHOTOURL VARCHAR(255),
		FACEBOOK VARCHAR(255),
		LINKEDIN VARCHAR(255),
		TWITTER VARCHAR(255),
		SPEAKERURL VARCHAR(255)
	);

CREATE TABLE SESSIONS (
		ID DECIMAL(19 , 2) NOT NULL,
		DETAILS VARCHAR(16384),
		ENDTIME TIMESTAMP NOT NULL,
		SESSIONURL VARCHAR(1024),
		STARTTIME TIMESTAMP NOT NULL,
		SUMMARY VARCHAR(4096),
		TITLE VARCHAR(255) NOT NULL,
		TYPE VARCHAR(16)
	);

CREATE TABLE CONFERENCES (
		ID DECIMAL(19 , 2) NOT NULL,
		ADDRESS VARCHAR(128) NOT NULL,
		CITY VARCHAR(64) NOT NULL,
		CONFERENCEURL VARCHAR(1024),
		COUNTRY VARCHAR(64) NOT NULL,
		DETAILS VARCHAR(4096),
		ENDDATE TIMESTAMP NOT NULL,
		LOGOURL VARCHAR(1024),
		REGION VARCHAR(64),
		STARTDATE TIMESTAMP NOT NULL,
		SUMMARY VARCHAR(1024),
		TITLE VARCHAR(255) NOT NULL,
		TIMEZONE VARCHAR(24) NOT NULL
	);

CREATE TABLE SESSIONS_SPEAKERS (
		SESSION_ID DECIMAL(19 , 2) NOT NULL,
		SPEAKER_ID DECIMAL(19 , 2) NOT NULL
	);

CREATE INDEX FK_AHFXM45R8OQG2J1YUDWXUX1X1_INDEX_F ON SESSIONS_SPEAKERS (SESSION_ID ASC);

CREATE INDEX FK_FMTOJ86BSI4FIFPGD2Q3TB3DQ_INDEX_B ON CONFERENCES_SESSIONS (CONFERENCE_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_8 ON SESSIONS (ID ASC);

CREATE INDEX FK_ERX1UGG0GLA8BEM0TOW1BWFXP_INDEX_F ON SESSIONS_SPEAKERS (SPEAKER_ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_C ON CONFERENCES (ID ASC);

CREATE UNIQUE INDEX PRIMARY_KEY_AF ON SPEAKERS (ID ASC);

CREATE UNIQUE INDEX UK_6L7VUCCLVDLXXVBL0MG1WU1SY_INDEX_B ON CONFERENCES_SESSIONS (SESSION_ID ASC);

ALTER TABLE SESSIONS ADD CONSTRAINT CONSTRAINT_8 PRIMARY KEY (ID);

ALTER TABLE SPEAKERS ADD CONSTRAINT CONSTRAINT_AF PRIMARY KEY (ID);

ALTER TABLE CONFERENCES ADD CONSTRAINT PRIMARY_KEY_C UNIQUE (ID);

ALTER TABLE CONFERENCES ADD CONSTRAINT CONSTRAINT_C PRIMARY KEY (ID);

ALTER TABLE SPEAKERS ADD CONSTRAINT PRIMARY_KEY_AF UNIQUE (ID);

ALTER TABLE SESSIONS ADD CONSTRAINT PRIMARY_KEY_8 UNIQUE (ID);

ALTER TABLE SESSIONS_SPEAKERS ADD CONSTRAINT FK_ERX1UGG0GLA8BEM0TOW1BWFXP FOREIGN KEY (SPEAKER_ID)
	REFERENCES SPEAKERS (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE CONFERENCES_SESSIONS ADD CONSTRAINT FK_6L7VUCCLVDLXXVBL0MG1WU1SY FOREIGN KEY (SESSION_ID)
	REFERENCES SESSIONS (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE SESSIONS_SPEAKERS ADD CONSTRAINT FK_AHFXM45R8OQG2J1YUDWXUX1X1 FOREIGN KEY (SESSION_ID)
	REFERENCES SESSIONS (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE CONFERENCES_SESSIONS ADD CONSTRAINT FK_FMTOJ86BSI4FIFPGD2Q3TB3DQ FOREIGN KEY (CONFERENCE_ID)
	REFERENCES CONFERENCES (ID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;