CREATE TABLE SPEAKERS (
	ID IDENTITY NOT NULL PRIMARY KEY,
	FIRSTNAME VARCHAR(64) NOT NULL,
	LASTNAME VARCHAR(64) NOT NULL,
	PHOTOURL VARCHAR(1024),
	SPEAKERURL VARCHAR(1024),
	ABOUT VARCHAR(4096),
	FACEBOOK VARCHAR(128),
	LINKEDIN VARCHAR(255),
	TWITTER VARCHAR(32),
);

CREATE TABLE SESSIONS (
	ID IDENTITY NOT NULL PRIMARY KEY,
	DETAILS VARCHAR(16384),
	ENDTIME TIMESTAMP NOT NULL,
	SESSIONURL VARCHAR(1024),
	STARTTIME TIMESTAMP NOT NULL,
	SUMMARY VARCHAR(4096),
	TITLE VARCHAR(255) NOT NULL,
	TYPE VARCHAR(16),
	TIMEZONE VARCHAR(24) NOT NULL
);

CREATE TABLE CONFERENCES (
	ID IDENTITY NOT NULL PRIMARY KEY,
	ADDRESS VARCHAR(128) NOT NULL,
	CITY VARCHAR(64) NOT NULL,
	CONFERENCEURL VARCHAR(1024),
	COUNTRY VARCHAR(64) NOT NULL,
	DETAILS VARCHAR(4096),
	ENDDATE TIMESTAMP NOT NULL,
	LOGOURL VARCHAR(1024),
	REGION VARCHAR(64),
	STARTDATE TIMESTAMP NOT NULL,
	SUMMARY VARCHAR(16384),
	TITLE VARCHAR(255) NOT NULL,
	TIMEZONE VARCHAR(24) NOT NULL
);

CREATE TABLE SESSIONS_SPEAKERS (
	SESSION_ID		BIGINT NOT NULL	REFERENCES SESSIONS(ID)
									ON DELETE CASCADE
									ON UPDATE CASCADE,
									
	SPEAKER_ID 		BIGINT NOT NULL	REFERENCES SPEAKERS(ID)
									ON DELETE CASCADE
									ON UPDATE CASCADE
);

CREATE TABLE CONFERENCES_SESSIONS (
	CONFERENCE_ID	BIGINT NOT NULL REFERENCES CONFERENCES(ID)
									ON DELETE CASCADE
									ON UPDATE CASCADE,

	SESSION_ID		BIGINT NOT NULL UNIQUE REFERENCES SESSIONS(ID)
									ON DELETE CASCADE
									ON UPDATE CASCADE
);