//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("Conferer")]
[assembly: System.Reflection.AssemblyCompany("Conferer")]
[assembly: System.Reflection.AssemblyTrademark("Conferer")]
[assembly: System.Reflection.AssemblyCopyright("©Conferer 2013")]
[assembly: System.Reflection.AssemblyVersion("1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0.e0741fa")]


